# Generated by Django 5.0.6 on 2024-06-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('genre', models.CharField(blank=True, choices=[('FAN', 'Fantasy'), ('NOI', 'Noir'), ('MYS', 'Mystery'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('ADV', 'Adventure'), ('ROM', 'Romance'), ('SAT', 'Satire'), ('CLA', 'Classic')], max_length=3)),
                ('release_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
