# Generated by Django 5.0.6 on 2024-06-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_release_date_book_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='start_date',
        ),
    ]
