# Generated by Django 5.0.6 on 2024-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_publish_date_book_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
