# Generated by Django 5.0.6 on 2024-07-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('FAN', 'Fantasy'), ('NOI', 'Noir'), ('MYS', 'Mystery'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('ADV', 'Adventure'), ('ROM', 'Romance'), ('SAT', 'Satire'), ('CLA', 'Classic'), ('PHI', 'Philosophy'), ('HIS', 'History')], max_length=3),
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.book')),
            ],
        ),
    ]
