# Generated by Django 5.0.6 on 2024-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_description_alter_book_genre_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fantasy', 'FAN'), ('Noir', 'NOI'), ('Mystery', 'MYS'), ('Horror', 'HOR'), ('Fiction', 'FIC'), ('Non-Fiction', 'NON'), ('Adventure', 'ADV'), ('Romance', 'ROM'), ('Satire', 'SAT'), ('Classic', 'CLA'), ('Philosophy', 'PHI'), ('History', 'HIS')], max_length=12),
        ),
    ]
