# Generated by Django 5.0.6 on 2024-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fantasy', 'Fantasy'), ('Noir', 'Noir'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non Fiction'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Classic', 'Classic'), ('Philosophy', 'Philosophy'), ('History', 'History')], max_length=64),
        ),
    ]
